version: 2.1
orbs:
  node: circleci/node@4.1
jobs:
  lint-and-build:
    docker:
      - image: circleci/node:14.17.5
    working_directory: /tmp/src
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm run build   
  test:
    docker:
      - image: circleci/node:14.17.5
    working_directory: /tmp/src
    steps:
      - checkout
      - run: npm ci
      - run: npm run test   

workflows:
  node-linters:
    jobs:
      - lint-and-build
      - test
